const interopDefault = r => r.default || r || []
export default {
  "../node_modules/nuxt/dist/app/entry.js": () => import('./_nuxt/entry-styles.BrfaHYqh.mjs').then(interopDefault),
  "../components/awesome/Form.vue": () => import('./_nuxt/Form-styles.T8u-GmiI.mjs').then(interopDefault),
  "../components/awesome/Products.vue": () => import('./_nuxt/Products-styles.C4JfvZ-7.mjs').then(interopDefault),
  "../components/awesome/Subscription.vue": () => import('./_nuxt/Subscription-styles.8XaNBrRL.mjs').then(interopDefault),
  "../components/awesome/lamp.vue": () => import('./_nuxt/lamp-styles.bem-V0Ip.mjs').then(interopDefault),
  "../components/awesome/Form.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/Form-styles.T8u-GmiI.mjs').then(interopDefault),
  "../components/awesome/Subscription.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/Subscription-styles.8XaNBrRL.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue": () => import('./_nuxt/welcome-styles.1iWpT8Sx.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-404.vue": () => import('./_nuxt/error-404-styles.DiyQGQgf.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-500.vue": () => import('./_nuxt/error-500-styles.D-Y5Iqvq.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-404.vue?vue&type=style&index=0&scoped=8e38b8ef&lang.css": () => import('./_nuxt/error-404-styles.DiyQGQgf.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/error-500.vue?vue&type=style&index=0&scoped=5741bfc2&lang.css": () => import('./_nuxt/error-500-styles.D-Y5Iqvq.mjs').then(interopDefault),
  "../components/awesome/Products.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/Products-styles.C4JfvZ-7.mjs').then(interopDefault),
  "../components/awesome/lamp.vue?vue&type=style&index=0&scoped=787b1300&lang.css": () => import('./_nuxt/lamp-styles.bem-V0Ip.mjs').then(interopDefault),
  "../components/awesome/Form/Switch.vue": () => import('./_nuxt/Switch-styles.BjRB6YNk.mjs').then(interopDefault),
  "../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue": () => import('./_nuxt/ProseCode-styles.BaOCvZyF.mjs').then(interopDefault),
  "../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/ProseCode-styles.BaOCvZyF.mjs').then(interopDefault),
  "../components/awesome/Form/Switch.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/Switch-styles.BjRB6YNk.mjs').then(interopDefault),
  "../components/awesome/Welcome.vue": () => import('./_nuxt/Welcome-styles.5p4XaYOk.mjs').then(interopDefault),
  "../components/awesome/Welcome.vue?vue&type=style&index=0&lang.scss": () => import('./_nuxt/Welcome-styles.5p4XaYOk.mjs').then(interopDefault),
  "../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue": () => import('./_nuxt/ProsePre-styles.CQChdepm.mjs').then(interopDefault),
  "../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue?vue&type=style&index=0&lang.css": () => import('./_nuxt/ProsePre-styles.CQChdepm.mjs').then(interopDefault),
  "../node_modules/nuxt-icon/dist/runtime/IconCSS.vue": () => import('./_nuxt/IconCSS-styles.dv5itu6T.mjs').then(interopDefault),
  "../node_modules/nuxt-icon/dist/runtime/Icon.vue": () => import('./_nuxt/Icon-styles.BvZSHInw.mjs').then(interopDefault),
  "../node_modules/nuxt-icon/dist/runtime/IconCSS.vue?vue&type=style&index=0&scoped=70cea3be&lang.css": () => import('./_nuxt/IconCSS-styles.dv5itu6T.mjs').then(interopDefault),
  "../node_modules/nuxt-icon/dist/runtime/Icon.vue?vue&type=style&index=0&scoped=7b58072b&lang.css": () => import('./_nuxt/Icon-styles.BvZSHInw.mjs').then(interopDefault),
  "../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue?vue&type=style&index=0&scoped=46326706&lang.css": () => import('./_nuxt/welcome-styles.1iWpT8Sx.mjs').then(interopDefault)
}